version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/runtime/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    labels: ["type:chore", "area:runtime"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels: ["type:chore", "area:ci"]
