"""SMTP send + IMAP poll. Stdlib only."""
from __future__ import annotations

import imaplib
import smtplib
import ssl
import time
from datetime import datetime, timezone
from email import message_from_bytes
from email.message import EmailMessage
from email.utils import formataddr, make_msgid
from pathlib import Path

from .config import Config


# ----- send -----

def build_message(
    cfg: Config,
    agent: str,
    subject: str,
    body: str,
    model_name: str,
) -> EmailMessage:
    msg = EmailMessage()
    from_display = f"{agent} via Tritium"
    msg["From"] = formataddr((from_display, cfg.smtp_user))
    msg["To"] = cfg.email_to_scotty
    msg["Subject"] = subject if subject.startswith("[Tritium") else f"[Tritium / {agent}] {subject}"
    msg["Message-ID"] = make_msgid(domain="tritium.local")
    msg["Date"] = datetime.now(timezone.utc).strftime("%a, %d %b %Y %H:%M:%S +0000")
    msg["X-Tritium-Agent"] = agent
    msg["X-Tritium-Model"] = model_name

    footer = (
        "\n\n--\n"
        f"Generated by {agent}'s persona via local LM Studio "
        f"(model: {model_name}) - Tritium Bridge\n"
    )
    msg.set_content(body.rstrip() + footer)
    return msg


def send_smtp(cfg: Config, msg: EmailMessage) -> str:
    """Send via STARTTLS or SSL. Returns the Message-ID on success."""
    ctx = ssl.create_default_context()
    if cfg.smtp_encryption == "SSL":
        with smtplib.SMTP_SSL(cfg.smtp_host, cfg.smtp_port, context=ctx, timeout=30) as s:
            s.login(cfg.smtp_user, cfg.smtp_pass)
            s.send_message(msg)
    else:  # STARTTLS or PLAIN
        with smtplib.SMTP(cfg.smtp_host, cfg.smtp_port, timeout=30) as s:
            s.ehlo()
            if cfg.smtp_encryption == "STARTTLS":
                s.starttls(context=ctx)
                s.ehlo()
            s.login(cfg.smtp_user, cfg.smtp_pass)
            s.send_message(msg)
    return msg["Message-ID"]


def archive_sent(cfg: Config, agent: str, msg: EmailMessage, slug: str) -> Path:
    sent_dir = cfg.repo_root / "sent"
    sent_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    safe_slug = "".join(c if c.isalnum() or c in "-_" else "-" for c in slug.lower())[:60]
    out = sent_dir / f"{ts}--{agent.lower()}--{safe_slug}.eml"
    out.write_bytes(bytes(msg))
    return out


def archive_outbox(cfg: Config, agent: str, msg: EmailMessage, slug: str, error: str) -> Path:
    out_dir = cfg.repo_root / "outbox"
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d-%H%M%S")
    safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in slug.lower())[:60]
    f = out_dir / f"{ts}--{agent.lower()}--{safe}.eml"
    payload = bytes(msg) + f"\n\nX-Bridge-Error: {error}\n".encode()
    f.write_bytes(payload)
    return f


# ----- receive -----

def poll_imap(cfg: Config) -> list[Path]:
    """Fetch unread mail from Scotty, save raw .eml to social hub inbox, mark read.
    Returns list of saved paths."""
    inbox_dir = cfg.social_hub / "inbox-from-scotty"
    inbox_dir.mkdir(parents=True, exist_ok=True)
    saved: list[Path] = []

    try:
        m = imaplib.IMAP4_SSL(cfg.imap_host, cfg.imap_port, timeout=30)
    except Exception as e:
        raise RuntimeError(f"IMAP connect failed: {e}") from e

    try:
        m.login(cfg.imap_user, cfg.imap_pass)
        m.select("INBOX")
        # UNSEEN messages from Scotty's address.
        typ, data = m.search(None, "UNSEEN", "FROM", cfg.email_to_scotty)
        if typ != "OK":
            return saved
        for num in data[0].split():
            typ, fetched = m.fetch(num, "(RFC822)")
            if typ != "OK" or not fetched or not fetched[0]:
                continue
            raw = fetched[0][1]
            parsed = message_from_bytes(raw)
            subject = parsed.get("Subject", "(no subject)")
            ts = datetime.now().strftime("%Y%m%d-%H%M%S")
            safe = "".join(c if c.isalnum() or c in "-_" else "-" for c in subject.lower())[:50]
            path = inbox_dir / f"{ts}--from-scotty--{safe}.eml"
            path.write_bytes(raw)
            saved.append(path)
            m.store(num, "+FLAGS", "\\Seen")
            time.sleep(0.05)
    finally:
        try:
            m.logout()
        except Exception:
            pass
    return saved
